### ISSUE TITLE
Is there any way to access the `annex` container?

### ISSUE THREAD

**Issue by tomekwi** [Schnouki/git-annex-remote-hubic#4]
Hello again,

I’ve been using your project for a good while now and it’s doing a fantastic job! It didn’t hurt my child a bit – but I have no cats to test it out on :) Just wanted to say thanks :)

Now down to business. As you advised I’ve been storing all my files in a container other than `default` (namely `annex`). Now I must admit I’ve forgotten the name of the folder I sent my data to. Do you know of any way to list the contents of a hubic container?

**Comment by vanicat** [comment]
If you have swift install, do as it is wrote in README:

    export GIT_ANNEX_HUBIC_AUTH_FILE=/path/to/auth/file
    source /path/to/auth/file

Then you have `swift list` to have a list of your containers, and `swift list annex` to list the content of the annex container.

Note that it's best to delete the file `/path/to/auth/file` because it contain  everything needed to access to your hubic account.

**Comment by tomekwi** [comment]
Oh, I missed that. Thanks! :)

**Comment by tomekwi** [comment]
I now got down to this and have problems with the `swift` command. I installed the pip package `python-swiftclient`, but here’s what I get after running any `swift …` command:

```
$ swift list
Traceback (most recent call last):
  File "~/.local/bin/swift", line 7, in <module>
    from swiftclient.shell import main
  File "~/.local/lib/python3.4/site-packages/swiftclient/shell.py", line 31, in <module>
    from swiftclient.multithreading import OutputManager
  File "~/.local/lib/python3.4/site-packages/swiftclient/multithreading.py", line 21, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "~/.local/lib/python3.4/site-packages/futures-3.0.3-py3.4.egg/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "~/.local/lib/python3.4/site-packages/futures-3.0.3-py3.4.egg/concurrent/futures/_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
```

I’ve tried out different `swift` commands and installed different versions of the package (2.4.0, 2.3.1 and 2.3.0) both as user and as root. Nothing has helped so far. I know this issue doesn’t belong here – but maybe one of you @Schnouki @vanicat have run into similar issues? I’m no experienced pythonist.
